name: http_io
version: 0.10.0-dev
author: "Dart Team <misc@dartlang.org>"
homepage: https://github.com/dart-lang/http_io
description: HTTP Client and Server APIs.
environment:
  sdk: ">=1.24.0 <2.0.0"
dependencies:
  crypto: "^2.0.2+1"
dev_dependencies:
  convert: "^2.0.1"
  test: "^0.12.18"
